load-flow:
  default-impl-name: Hades2

computation-local:
    tmp-dir: /tmp
    availableCore: 1

hades2:
    homeDir: /home/tilloyann/simulators/hades2/hades2-V6.7.1.1/
    debug: true

load-flow-default-parameters:
    voltageInitMode: DC_VALUES
    transformerVoltageControlOn: false
    specificCompatibility: true

hades2-default-parameters:
    dcMode: false

hades2-default-sensitivity-parameters:
    computeInitialLoadflow: true
    computeSensitivityToPsts: true
    computeSensitivityToInjections: false
    resultsThreshold: 0

sensitivity-analysis:
  default-impl-name: "Sensi2"
