componentDefaultConfig:
    LoadFlowFactory: com.rte_france.powsybl.hades2.Hades2Factory
    SecurityAnalysisFactory: com.rte_france.powsybl.hades2.Hades2SecurityAnalysisFactory
    ContingenciesProviderFactory: com.powsybl.action.dsl.GroovyDslContingenciesProviderFactory
    
#computation-local:
#    localDir: <path_to_local_tmp>
#    availableCore: 1
#
#hades2:
#  homeDir: <path_to_hades_2>
#  timeout: 120
#  debug: true
#  useSAX: false