componentDefaultConfig:
    LoadFlowFactory: com.rte_france.powsybl.hades2.Hades2Factory
    SecurityAnalysisFactory: com.rte_france.powsybl.hades2.Hades2SecurityAnalysisFactory
    ContingenciesProviderFactory: com.powsybl.action.dsl.GroovyDslContingenciesProviderFactory
    
computation-local:
    tmp-dir: /tmp/sensitivity
    availableCore: 1

hades2:
    homeDir: /home/leroyagn/projects/modeles/hades2_distributions/hades2-V6.4.0.1.1/
    debug: true
    useSAX: true

hades2-default-parameters:
    dcMode: true
    balanceType: PROPORTIONAL_TO_GENERATION_P
    countriesToBalance: BE,DE,FR,NL

hades2-default-sensitivity-parameters:
    computeInitialLoadflow: true
    computeSensitivityToPsts: true
    computeSensitivityToInjections: true
    equationTypePst: ANGLE_SHIFT_EQ
    resultsThreshold: -1
    hubPtdf: -1

load-flow-default-parameters:
    voltageInitMode: DC_VALUES
    transformerVoltageControlOn: false
    specificCompatibility: true
