load-flow:
  default-impl-name: OpenLoadFlow

computation-local:
    tmp-dir: /tmp
    availableCore: 1

load-flow-default-parameters:
    voltageInitMode: DC_VALUES
    transformerVoltageControlOn: false
    specificCompatibility: true
