metrix:
  iidm-export-version: "1.13" # default to latest available version
  ignoreEmptyFilter: true

load-flow:
  default-impl-name: "OpenLoadFlow"

load-flow-default-parameters:
  dc: true

open-loadflow-default-parameters:
  slackBusSelectorType: Name
  nameSlackBusSelectorBusId: VLHV2_0