load-flow:
  default-impl-name: "OpenLoadFlow"

open-loadflow-default-parameters:
  remainsLoadPowerFactorConstant: false
  lowImpedanceBranchMode: REPLACE_BY_ZERO_IMPEDANCE_LINE
  throwsExceptionInCaseOfSlackDistributionFailure: false
  voltageRemoteControl: true
  slackBusSelectorType: MostMeshed
  dcUseTransformerRatio: false
  
import-export-parameters-default-value:
  iidm.import.cgmes.boundary-location: path-to-EQBD-TPBD
  iidm.import.cgmes.profile-used-for-initial-state-values: SSH
  iidm.import.cgmes.store-cgmes-conversion-context-as-network-extension: true
  iidm.export.xml.version: "1.5"
  iidm.import.cgmes.ensure-id-alias-unicity: true
  iidm.import.cgmes.create-cgmes-export-mapping: true
  
  
balances-adjustment-validation-parameters:
  data-exchanges-path: path-to-PEVF

  igm-paths:
    - IGM1-name, path-to-IGM1
    - IGM2-name, path-to-IGM2

  output-dir: path-to-directory

